/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import java.awt.Color;
/**
 *
 * @author RESCOM-1
 */
public class buatpasswordbaru extends javax.swing.JPanel {

    /**
     * Creates new form buatpasswordbaru
     */
    public buatpasswordbaru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnubahpassword = new javax.swing.JLabel();
        inputpassword1 = new javax.swing.JTextField();
        inputpassword2 = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setLayout(null);

        btnubahpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnubahpass1.png"))); // NOI18N
        btnubahpassword.setText("jLabel1");
        add(btnubahpassword);
        btnubahpassword.setBounds(410, 520, 560, 70);

        inputpassword1.setBackground(new Color(0,0,0,0));
        add(inputpassword1);
        inputpassword1.setBounds(480, 310, 400, 40);

        inputpassword2.setBackground(new Color(0,0,0,0));
        add(inputpassword2);
        inputpassword2.setBounds(480, 390, 400, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/ubah password.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnubahpassword;
    private javax.swing.JTextField inputpassword1;
    private javax.swing.JTextField inputpassword2;
    // End of variables declaration//GEN-END:variables
}
