/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import javax.swing.SwingUtilities;
import main.main;
//import main.main;
import repository.userRepository;
import service.Auth;


public class Login extends javax.swing.JPanel {
    userRepository ret = new userRepository();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnlogin = new javax.swing.JLabel();
        inputpassword = new javax.swing.JTextField();
        inputusername = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setLayout(null);

        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnlogin1.png"))); // NOI18N
        btnlogin.setText("jLabel2");
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });
        add(btnlogin);
        btnlogin.setBounds(410, 520, 550, 70);
        add(inputpassword);
        inputpassword.setBounds(490, 390, 400, 40);
        add(inputusername);
        inputusername.setBounds(490, 310, 400, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/login form.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1370, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    main apa = (main)SwingUtilities.getWindowAncestor(this);
//    apa.showkoko();
//    this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
    String user = inputusername.getText();
    String pass = inputpassword.getText();
        Auth ap = new Auth();
    if(ap.login(user, pass)){
        main wow = (main)SwingUtilities.getWindowAncestor(this);
        wow.showdasboard();
        this.setVisible(false);
    }else{
        System.out.println("gagal login");
    }
    }//GEN-LAST:event_btnloginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnlogin;
    private javax.swing.JTextField inputpassword;
    private javax.swing.JTextField inputusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
