/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import javax.swing.SwingUtilities;
import main.main;

/**
 *
 * @author semafie
 */
public class pasienbaru extends javax.swing.JPanel {

    /**
     * Creates new form pasienbaru
     */
    public pasienbaru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kembali = new javax.swing.JLabel();
        btn_lanjut = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        ttl = new javax.swing.JTextField();
        nama_pasien = new javax.swing.JTextField();
        no_rm = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();

        setLayout(null);

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali1.png"))); // NOI18N
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        add(btn_kembali);
        btn_kembali.setBounds(10, 710, 190, 51);

        btn_lanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        add(btn_lanjut);
        btn_lanjut.setBounds(1110, 710, 250, 51);
        add(nik);
        nik.setBounds(550, 390, 490, 40);
        add(alamat);
        alamat.setBounds(550, 460, 490, 40);
        add(ttl);
        ttl.setBounds(550, 530, 490, 40);
        add(nama_pasien);
        nama_pasien.setBounds(550, 320, 490, 40);
        add(no_rm);
        no_rm.setBounds(550, 250, 490, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki- Laki", "Perempuan" }));
        add(jComboBox1);
        jComboBox1.setBounds(570, 600, 280, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/Pasien Baru.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdasboard();
    }//GEN-LAST:event_btn_kembaliMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_lanjut;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField no_rm;
    private javax.swing.JTextField ttl;
    // End of variables declaration//GEN-END:variables
}
