/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.swing;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import panel.buatpasswordbaru;
import service.Auth;
import util.Conn;
import java.awt.Color;
/**
 *
 * @author RESCOM-1
 */
public class dialog_mintakode extends Dialog {

    /**
     * Creates new form NewJDialog
     */
    Auth a = new Auth();
    private String username = a.username;
    public dialog_mintakode(JFrame fram) {
        super(fram);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnverif = new javax.swing.JLabel();
        inputverifikasi = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnverif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnverifikasi1.png"))); // NOI18N
        btnverif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnverifMouseClicked(evt);
            }
        });
        getContentPane().add(btnverif);
        btnverif.setBounds(470, 510, 426, 80);

        inputverifikasi.setBackground(new Color(0,0,0,0));
        inputverifikasi.setBorder(null);
        getContentPane().add(inputverifikasi);
        inputverifikasi.setBounds(490, 360, 390, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/verifikasi kode.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1050, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnverifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverifMouseClicked
        String token = inputverifikasi.getText();

        String queryCek = "SELECT token FROM user WHERE username = ?";

        try {
            Connection koneksi = (Connection) Conn.configDB();
            PreparedStatement pst = koneksi.prepareStatement(queryCek);
            pst.setString(1, username);
            ResultSet res = pst.executeQuery();
            if(res.next()){
                if(inputverifikasi.getText().equals(res.getString("token"))){

                    a.hapusToken(username);
                    a.username = "";
                    buatpasswordbaru apa = new buatpasswordbaru();
                    this.setVisible(false);
                    apa.setVisible(true);

                }else{

                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnverifMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnverif;
    private javax.swing.JTextField inputverifikasi;
    // End of variables declaration//GEN-END:variables
}
